name: mental-health-ci

on:
  push:
    paths:
      - 'MLproject'
      - 'conda.yaml'
      - '.github/workflows/ci.yml'
      - 'modelling.py'
    branches:
      - main

  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mental-health-ci
          environment-file: conda.yaml
          auto-update-conda: true
          auto-activate-base: false

      - name: Install dotenv
        run: conda install -c conda-forge python-dotenv

      - name: Run MLProject with MLflow
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate mental-health-ci
          mlflow run . --env-manager=local -P n_estimators=100 -P random_state=42

      - name: Commit and Push .mlruns artifacts
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add MLProject/.mlruns || echo "No changes"
          git commit -m "Add MLflow run artifacts [skip ci]" || echo "No changes to commit"
          git push || echo "Nothing to push"

      - name: Build Docker Image from MLflow Model
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate mental-health-ci
          latest_run=$(ls .mlruns/0 | head -n 1)
          echo "Building Docker image for run: $latest_run"
          docker build -t nfvalennn/mental-health-mlflow:latest
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker tag mental-health-mlflow:latest nfvalennn/mental-health-mlflow:latest && docker push nfvalennn/mental-health-mlflow:latest
